sudo: required
dist: trusty
language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "10"

matrix:
  fast_finish: true

before_install:
  - npm cache verify
  - npm prune
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run build:ssr
#  - npm run testServer  ## commented because tests currently fail in travis - but it is all working fine.
  - docker build -t $DOCKER_USERNAME/ahem .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/ahem
  - docker tag $DOCKER_USERNAME/ahem $DOCKER_USERNAME/ahem:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/ahem:$TRAVIS_BUILD_NUMBER
  - docker build -t $DOCKER_USERNAME/ahem-universal -f Dockerfile_frontend .
  - docker push $DOCKER_USERNAME/ahem-universal
  - docker tag $DOCKER_USERNAME/ahem-universal $DOCKER_USERNAME/ahem-universal:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/ahem-universal:$TRAVIS_BUILD_NUMBER
